name: GitHub Pages Deployment

on:
    push:
        branches:
            - main # oder dein Branch, der für GitHub Pages verwendet wird

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
